INSERT INTO products ( name, price, category, description, image_url, in_stock)
VALUES
  ( 'Ficus benjamina Braid Extra Large', 29500,'indoor plants', 'The Ficus benjamina Braid is an extra-large plant that adds a unique touch to any space. It features twisted, braided stems and lush foliage, making it a beautiful addition to your indoor garden.','https://cdn.shopify.com/s/files/1/0253/6701/9565/products/Ficus-Benjamina-Braid-Grow-Pot-Extra-Large.jpg?v=1681052730',5),
   ('Norfolk Island Pine', 1950,'indoor plants', 'The Norfolk Island Pine is a charming plant that resembles a miniature Christmas tree. It is a low-maintenance indoor plant that brings a festive vibe to any room with its graceful branches and soft needles.', 'https://cdn.shopify.com/s/files/1/0253/6701/9565/products/Detail-Ficus-Benjamina-Braid-Grow-Pot-Extra-Large.jpg?v=1681052730',5),
  ( 'Bird of Paradise', 9900,'indoor plants', 'The Bird of Paradise plant is known for its stunning tropical foliage and vibrant flowers. It adds a touch of exotic beauty to any space and thrives in bright indoor locations. Enjoy the elegance and allure of this magnificent plant.', 'https://cdn.shopify.com/s/files/1/0253/6701/9565/products/Bird-of-Paradise-Grow-Pot-Extra-Large.jpg?v=1657137315',6),
  ( 'ZZ Plant', 3200,'indoor plants', 'The ZZ Plant, also known as Zamioculcas zamiifolia, is a popular choice for indoor gardening enthusiasts. Its glossy, dark green leaves add a touch of elegance to any room, and it is known for its ability to tolerate low-light conditions.', 'https://cdn.shopify.com/s/files/1/0253/6701/9565/products/ZZ-Plant-Grow-Pot-Extra-Large.jpg?v=1657137493',5),
  ( 'Rubber Tree Burgundy', 5500,'indoor plants', 'The Rubber Tree Burgundy is a stunning plant with glossy, burgundy-colored leaves. It adds a touch of drama and sophistication to any space, making it a perfect choice for plant lovers looking to make a statement.', 'https://cdn.shopify.com/s/files/1/0253/6701/9565/products/Rubber-Tree-Burgundy-Grow-Pot-Extra-Large.jpg?v=1680140786',3),
  ( 'Monstera Deliciosa', 6900,'indoor plants', 'The Monstera Deliciosa, also known as the Swiss Cheese Plant, is a popular choice for plant enthusiasts. Its large, fenestrated leaves make it a striking addition to any space, and it thrives in both bright and indirect light conditions.', 'https://cdn.shopify.com/s/files/1/0253/6701/9565/products/Monstera-Deliciosa-Grow-Pot-Extra-Large.jpg?v=1657136337',0),
  ( 'Snake Plant Laurentii', 2500, 'indoor plants','The Snake Plant Laurentii, also known as Sansevieria, is a popular and resilient plant. It has tall, variegated leaves that add a touch of modern elegance to any space, and it is known for its air-purifying qualities.', 'https://cdn.shopify.com/s/files/1/0253/6701/9565/products/Snake-Plant-Laurentii-Grow-Pot-Extra-Large.jpg?v=1657137244',6),
  ( 'Pothos Golden', 1800,'indoor plants', 'The Pothos Golden is a popular trailing plant known for its vibrant golden-yellow leaves. It is an easy-to-care-for plant that adds a pop of color and a cascading effect to any room or hanging basket.', 'https://cdn.shopify.com/s/files/1/0253/6701/9565/products/Pothos-Golden-Grow-Pot-Extra-Large.jpg?v=1657136997',1),
  ( 'Peace Lily', 3800,'indoor plants', 'The Peace Lily, also known as Spathiphyllum, is a popular choice for indoor plants. It features elegant white flowers and lush green foliage, adding a touch of serenity and beauty to any space.', 'https://cdn.shopify.com/s/files/1/0253/6701/9565/products/Peace-Lily-Grow-Pot-Extra-Large.jpg?v=1657137189',3),
  ('Red Mandevilla', 6500, 'flowering plants', 'This radiant Red Mandevilla will bring the beauty of the outdoors right to your living space. This low-maintenance, sun-loving vine has vibrant red flowers that will take your home décor to the next level. Brighten up your home or patio with this tropical beauty and enjoy its colorful foliage for years to come.', 'https://cdn.shopify.com/s/files/1/0253/6701/9565/files/Red-Mandevilla-Grow-Pot-Extra-Large.jpg?v=1683821303', 1),
  ('Aechmea Picante', 6900, 'flowering plants', 'Spice up your home with Aechmea Picante! This neon pink bromeliad provides a totally 80s throwback feel but with low-maintenance care: give it bright light, regular water, and some funky keyboard tunes and youre good to go! Get your daily dose of colorful', 'https://cdn.shopify.com/s/files/1/0253/6701/9565/files/Aechmea-Picante-Grow-pot-Large.jpg?v=1684192374', 1),
  ('Coral Anthurium - Small / Cylinder', 5500, 'flowering plants', 'Small-sized Coral Anthurium plant in a Cylinder pot.', 'https://cdn.shopify.com/s/files/1/0253/6701/9565/products/Anthurium-Coral-Cylinder-Pot-Small.jpg?v=1627566740', 1),
  ('Purple Anthurium', 29.50, 'flowering plants', 'These flowering indoor plants feature a color explosion in a range of stunning hues. Mix them together to create a mood-altering visual experience with deep reds, soft pinks, pure whites and glossy purples standing above rich green heart-shaped leaves.', 'https://cdn.shopify.com/s/files/1/0253/6701/9565/products/Anthurium-Purple-Grow-Pot-Small_2ab783fc-ea80-4a43-971a-8876cdc9aa31.jpg?v=1657917350', 1),
  ('Peace Lily Jetty - Large / Organic', 12000, 'flowering plants', 'Peace Lily Jetty brings on the bloom this spring! These elongated, magical spires announce their presence with a tall glowing exclamation.', 'https://cdn.shopify.com/s/files/1/0253/6701/9565/products/Peace-Lily-Jetty-Grow-Pot-Small.jpg?v=1676729532', 1),
  ('Red Flowering Holiday Cactus', 1500, 'flowering plants', 'Schlumbergera truncata (very similar to the Christmas Cactus', 'https://cdn.shopify.com/s/files/1/0253/6701/9565/products/Red-Flowering-Holiday-Cactus.jpg?v=1676729532', 1);
INSERT INTO users (username,password,email,image_url,type) VALUES('admin','$2b$07$NcDas0M/6aSZbdTzsbK0quCE8N0uHkAxHCotnDY3Vpma7k2wbsnxa','admin1@gmail.com','https://th.bing.com/th/id/R.7f70ccdaea42a3ea7f34f470040c1b29?rik=XpAJhC2Net1BXg&pid=ImgRaw&r=0','admin')

