INSERT INTO products (user_id, name, price, category, description, image_url, in_stock)
VALUES
(1, 'Ficus benjamina Braid Extra Large', 29500, 'indoor plants', 'The Ficus benjamina Braid is an extra-large plant with twisted, braided stems and lush foliage, perfect for indoor gardens.', 'https://cdn.shopify.com/s/files/1/0253/6701/9565/products/Ficus-Benjamina-Braid-Grow-Pot-Extra-Large.jpg?v=1681052730', 5),
(1, 'Norfolk Island Pine', 1950, 'indoor plants', 'The Norfolk Island Pine is a low-maintenance indoor plant that resembles a miniature Christmas tree, adding a festive vibe to any room.', 'https://cdn.shopify.com/s/files/1/0253/6701/9565/products/Detail-Ficus-Benjamina-Braid-Grow-Pot-Extra-Large.jpg?v=1681052730', 5),
(1, 'Bird of Paradise', 9900, 'indoor plants', 'The Bird of Paradise plant features stunning tropical foliage and vibrant flowers, adding an exotic touch to any space.', 'https://cdn.shopify.com/s/files/1/0253/6701/9565/products/Bird-of-Paradise-Grow-Pot-Extra-Large.jpg?v=1657137315', 6),
(1, 'ZZ Plant', 3200, 'indoor plants', 'The ZZ Plant, also known as Zamioculcas zamiifolia, is a popular choice for indoor gardening with glossy, dark green leaves that thrive in low-light conditions.', 'https://cdn.shopify.com/s/files/1/0253/6701/9565/products/ZZ-Plant-Grow-Pot-Extra-Large.jpg?v=1657137493', 5),
(1, 'Rubber Tree Burgundy', 5500, 'indoor plants', 'The Rubber Tree Burgundy is a stunning plant with glossy, burgundy-colored leaves, perfect for plant lovers looking to make a statement.', 'https://cdn.shopify.com/s/files/1/0253/6701/9565/products/Rubber-Tree-Burgundy-Grow-Pot-Extra-Large.jpg?v=1680140786', 3),
(1, 'Monstera Deliciosa', 6900, 'indoor plants', 'The Monstera Deliciosa, also known as the Swiss Cheese Plant, is a striking addition to any space with its large, fenestrated leaves.', 'https://cdn.shopify.com/s/files/1/0253/6701/9565/products/Monstera-Deliciosa-Grow-Pot-Extra-Large.jpg?v=1657136337', 0),
(1, 'Snake Plant Laurentii', 2500, 'indoor plants', 'The Snake Plant Laurentii, also known as Sansevieria, is a popular and resilient plant with tall, variegated leaves that add modern elegance.', 'https://cdn.shopify.com/s/files/1/0253/6701/9565/products/Snake-Plant-Laurentii-Grow-Pot-Extra-Large.jpg?v=1657137244', 6),
(1, 'Pothos Golden', 1800, 'indoor plants', 'The Pothos Golden is a popular trailing plant with vibrant golden-yellow leaves that add a pop of color and a cascading effect to any room.', 'https://cdn.shopify.com/s/files/1/0253/6701/9565/products/Pothos-Golden-Grow-Pot-Extra-Large.jpg?v=1657136997', 1),
(1, 'Peace Lily', 3800, 'indoor plants', 'The Peace Lily, also known as Spathiphyllum, features elegant white flowers and lush green foliage, adding serenity and beauty to any space.', 'https://cdn.shopify.com/s/files/1/0253/6701/9565/products/Peace-Lily-Grow-Pot-Extra-Large.jpg?v=1657137189', 3),
(1, 'Red Mandevilla', 6500, 'flowering plants', 'The Red Mandevilla is a low-maintenance, sun-loving vine with vibrant red flowers, perfect for brightening up your home or patio.', 'https://cdn.shopify.com/s/files/1/0253/6701/9565/files/Red-Mandevilla-Grow-Pot-Extra-Large.jpg?v=1683821303', 1),
(1, 'Aechmea Picante', 6900, 'flowering plants', 'Aechmea Picante is a neon pink bromeliad that brings a totally 80s throwback feel to your home, requiring low-maintenance care.', 'https://cdn.shopify.com/s/files/1/0253/6701/9565/files/Aechmea-Picante-Grow-pot-Large.jpg?v=1684192374', 1),
(1, 'Coral Anthurium - Small / Cylinder', 5500, 'flowering plants', 'Small-sized Coral Anthurium plant in a Cylinder pot.', 'https://cdn.shopify.com/s/files/1/0253/6701/9565/products/Anthurium-Coral-Cylinder-Pot-Small.jpg?v=1627566740', 1),
(1, 'Purple Anthurium', 29.50, 'flowering plants', 'Purple Anthurium plants feature a color explosion with deep reds, soft pinks, pure whites, and glossy purples standing above rich green heart-shaped leaves.', 'https://cdn.shopify.com/s/files/1/0253/6701/9565/products/Anthurium-Purple-Grow-Pot-Small_2ab783fc-ea80-4a43-971a-8876cdc9aa31.jpg?v=1657917350', 1),
(1, 'Peace Lily Jetty - Large / Organic', 12000, 'flowering plants', 'Peace Lily Jetty features tall glowing spires, bringing bloom and beauty to your space.', 'https://cdn.shopify.com/s/files/1/0253/6701/9565/products/Peace-Lily-Jetty-Grow-Pot-Small.jpg?v=1676729532', 1),
(1, 'Red Flowering Holiday Cactus', 1500, 'flowering plants', 'Schlumbergera truncata (similar to the Christmas Cactus) with red flowers.', 'https://cdn.shopify.com/s/files/1/0253/6701/9565/products/Red-Flowering-Holiday-Cactus.jpg?v=1676729532', 1);

